---
name: "Network Integration Tests"

concurrency:
  group: integration-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - 'stable-*'
  workflow_dispatch:

jobs:
  network-integration:
    name: Network Integration Tests
    runs-on: [self-hosted]
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        target:
          - splunk_adaptive_response_notable_events
          - splunk_correlation_searches
          - splunk_data_inputs_monitor
          - splunk_data_inputs_network
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ansible_collections/splunk/es

      - name: Install ansible-core
        run: |
          source ~/venv-runner/bin/activate
          pip install ansible-core

      - name: Install collection dependencies
        run: |
          source ~/venv-runner/bin/activate
          ansible-galaxy collection install ansible.netcommon ansible.utils -p ./ansible_collections

      - name: Generate inventory file
        working-directory: ansible_collections/splunk/es
        run: tests/integration/generate_inventory.sh
        env:
          SPLUNK_HOSTNAME: ${{ secrets.SPLUNK_HOSTNAME }}
          SPLUNK_USERNAME: ${{ secrets.SPLUNK_USERNAME }}
          SPLUNK_PASSWORD: ${{ secrets.SPLUNK_PASSWORD }}

      - name: Run network integration tests
        working-directory: ansible_collections/splunk/es
        run: |
          source ~/venv-runner/bin/activate
          ansible-test network-integration ${{ matrix.target }} -v --color yes
