---
name: "Network Integration Tests"

concurrency:
  group: integration-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request_target:
    branches: [main]
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - "plugins/**"
      - "tests/integration/**"
  workflow_dispatch:

jobs:
  safe-to-test:
    if: >-
      github.event.label.name == 'safe to test' ||
      github.event.action != 'labeled'
    uses: ansible-network/github_actions/.github/workflows/safe-to-test.yml@main

  network-integration:
    name: Network Integration Tests
    runs-on: [self-hosted]
    needs:
      - safe-to-test
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ansible_collections/splunk/es

      - name: Install ansible-core
        run: |
          source ~/venv-runner/bin/activate
          pip install ansible-core

      - name: Install collection dependencies
        run: |
          source ~/venv-runner/bin/activate
          ansible-galaxy collection install ansible.netcommon ansible.utils -p ./ansible_collections

      - name: Generate inventory file
        working-directory: ansible_collections/splunk/es
        run: tests/integration/generate_inventory.sh
        env:
          SPLUNK_HOSTNAME: ${{ secrets.SPLUNK_HOSTNAME }}
          SPLUNK_USERNAME: ${{ secrets.SPLUNK_USERNAME }}
          SPLUNK_PASSWORD: ${{ secrets.SPLUNK_PASSWORD }}

      - name: Run network integration tests
        working-directory: ansible_collections/splunk/es
        run: |
          source ~/venv-runner/bin/activate
          ansible-test network-integration -v --color yes
